// ============================================================
// 自動生成 — 手で編集しないこと (#202)
//
// 生成元: https://raw.githubusercontent.com/misode/mcmeta/1.21.1-summary/item_components/data.json
// 生成コマンド: npm run gen-item-stacks
// Minecraft 1.21.1 / アイテム 1333 種
//   上限 1: 183 種 / 上限 16: 45 種 / 上限 64: 1105 種
//
// 表に無い ID は 64 として扱い、警告を出す (生成元より新しい / MOD のアイテム)。
// ============================================================

/** スタック上限 1 (スタック不可) のアイテム。 */
export const STACK_1_IDS: readonly string[] = [
  'acacia_boat', 'acacia_chest_boat', 'axolotl_bucket', 'bamboo_chest_raft', 'bamboo_raft',
  'beetroot_soup', 'birch_boat', 'birch_chest_boat', 'black_bed', 'black_shulker_box',
  'blue_bed', 'blue_shulker_box', 'bow', 'brown_bed', 'brown_shulker_box', 'brush',
  'bundle', 'cake', 'carrot_on_a_stick', 'chainmail_boots', 'chainmail_chestplate',
  'chainmail_helmet', 'chainmail_leggings', 'cherry_boat', 'cherry_chest_boat',
  'chest_minecart', 'cod_bucket', 'command_block_minecart', 'creeper_banner_pattern',
  'crossbow', 'cyan_bed', 'cyan_shulker_box', 'dark_oak_boat', 'dark_oak_chest_boat',
  'debug_stick', 'diamond_axe', 'diamond_boots', 'diamond_chestplate', 'diamond_helmet',
  'diamond_hoe', 'diamond_horse_armor', 'diamond_leggings', 'diamond_pickaxe',
  'diamond_shovel', 'diamond_sword', 'elytra', 'enchanted_book', 'fishing_rod',
  'flint_and_steel', 'flow_banner_pattern', 'flower_banner_pattern', 'furnace_minecart',
  'globe_banner_pattern', 'goat_horn', 'golden_axe', 'golden_boots', 'golden_chestplate',
  'golden_helmet', 'golden_hoe', 'golden_horse_armor', 'golden_leggings', 'golden_pickaxe',
  'golden_shovel', 'golden_sword', 'gray_bed', 'gray_shulker_box', 'green_bed',
  'green_shulker_box', 'guster_banner_pattern', 'hopper_minecart', 'iron_axe', 'iron_boots',
  'iron_chestplate', 'iron_helmet', 'iron_hoe', 'iron_horse_armor', 'iron_leggings',
  'iron_pickaxe', 'iron_shovel', 'iron_sword', 'jungle_boat', 'jungle_chest_boat',
  'knowledge_book', 'lava_bucket', 'leather_boots', 'leather_chestplate', 'leather_helmet',
  'leather_horse_armor', 'leather_leggings', 'light_blue_bed', 'light_blue_shulker_box',
  'light_gray_bed', 'light_gray_shulker_box', 'lime_bed', 'lime_shulker_box',
  'lingering_potion', 'mace', 'magenta_bed', 'magenta_shulker_box', 'mangrove_boat',
  'mangrove_chest_boat', 'milk_bucket', 'minecart', 'mojang_banner_pattern',
  'mushroom_stew', 'music_disc_11', 'music_disc_13', 'music_disc_5', 'music_disc_blocks',
  'music_disc_cat', 'music_disc_chirp', 'music_disc_creator',
  'music_disc_creator_music_box', 'music_disc_far', 'music_disc_mall', 'music_disc_mellohi',
  'music_disc_otherside', 'music_disc_pigstep', 'music_disc_precipice', 'music_disc_relic',
  'music_disc_stal', 'music_disc_strad', 'music_disc_wait', 'music_disc_ward',
  'netherite_axe', 'netherite_boots', 'netherite_chestplate', 'netherite_helmet',
  'netherite_hoe', 'netherite_leggings', 'netherite_pickaxe', 'netherite_shovel',
  'netherite_sword', 'oak_boat', 'oak_chest_boat', 'orange_bed', 'orange_shulker_box',
  'piglin_banner_pattern', 'pink_bed', 'pink_shulker_box', 'potion', 'powder_snow_bucket',
  'pufferfish_bucket', 'purple_bed', 'purple_shulker_box', 'rabbit_stew', 'red_bed',
  'red_shulker_box', 'saddle', 'salmon_bucket', 'shears', 'shield', 'shulker_box',
  'skull_banner_pattern', 'splash_potion', 'spruce_boat', 'spruce_chest_boat', 'spyglass',
  'stone_axe', 'stone_hoe', 'stone_pickaxe', 'stone_shovel', 'stone_sword',
  'suspicious_stew', 'tadpole_bucket', 'tnt_minecart', 'totem_of_undying', 'trident',
  'tropical_fish_bucket', 'turtle_helmet', 'warped_fungus_on_a_stick', 'water_bucket',
  'white_bed', 'white_shulker_box', 'wolf_armor', 'wooden_axe', 'wooden_hoe',
  'wooden_pickaxe', 'wooden_shovel', 'wooden_sword', 'writable_book', 'yellow_bed',
  'yellow_shulker_box',
]

/** スタック上限 16 のアイテム。 */
export const STACK_16_IDS: readonly string[] = [
  'acacia_hanging_sign', 'acacia_sign', 'armor_stand', 'bamboo_hanging_sign', 'bamboo_sign',
  'birch_hanging_sign', 'birch_sign', 'black_banner', 'blue_banner', 'brown_banner',
  'bucket', 'cherry_hanging_sign', 'cherry_sign', 'crimson_hanging_sign', 'crimson_sign',
  'cyan_banner', 'dark_oak_hanging_sign', 'dark_oak_sign', 'egg', 'ender_pearl',
  'gray_banner', 'green_banner', 'honey_bottle', 'jungle_hanging_sign', 'jungle_sign',
  'light_blue_banner', 'light_gray_banner', 'lime_banner', 'magenta_banner',
  'mangrove_hanging_sign', 'mangrove_sign', 'oak_hanging_sign', 'oak_sign', 'orange_banner',
  'pink_banner', 'purple_banner', 'red_banner', 'snowball', 'spruce_hanging_sign',
  'spruce_sign', 'warped_hanging_sign', 'warped_sign', 'white_banner', 'written_book',
  'yellow_banner',
]

/**
 * スタック上限 64 のアイテム。
 *
 * 判定自体は「1 でも 16 でもなければ 64」で足りるが、**未知アイテムの警告**を
 * 出すために「このバージョンに存在した ID」を知る必要があるので列挙する。
 */
export const STACK_64_IDS: readonly string[] = [
  'acacia_button', 'acacia_door', 'acacia_fence', 'acacia_fence_gate', 'acacia_leaves',
  'acacia_log', 'acacia_planks', 'acacia_pressure_plate', 'acacia_sapling', 'acacia_slab',
  'acacia_stairs', 'acacia_trapdoor', 'acacia_wood', 'activator_rail', 'air',
  'allay_spawn_egg', 'allium', 'amethyst_block', 'amethyst_cluster', 'amethyst_shard',
  'ancient_debris', 'andesite', 'andesite_slab', 'andesite_stairs', 'andesite_wall',
  'angler_pottery_sherd', 'anvil', 'apple', 'archer_pottery_sherd', 'armadillo_scute',
  'armadillo_spawn_egg', 'arms_up_pottery_sherd', 'arrow', 'axolotl_spawn_egg', 'azalea',
  'azalea_leaves', 'azure_bluet', 'baked_potato', 'bamboo', 'bamboo_block', 'bamboo_button',
  'bamboo_door', 'bamboo_fence', 'bamboo_fence_gate', 'bamboo_mosaic', 'bamboo_mosaic_slab',
  'bamboo_mosaic_stairs', 'bamboo_planks', 'bamboo_pressure_plate', 'bamboo_slab',
  'bamboo_stairs', 'bamboo_trapdoor', 'barrel', 'barrier', 'basalt', 'bat_spawn_egg',
  'beacon', 'bedrock', 'bee_nest', 'bee_spawn_egg', 'beef', 'beehive', 'beetroot',
  'beetroot_seeds', 'bell', 'big_dripleaf', 'birch_button', 'birch_door', 'birch_fence',
  'birch_fence_gate', 'birch_leaves', 'birch_log', 'birch_planks', 'birch_pressure_plate',
  'birch_sapling', 'birch_slab', 'birch_stairs', 'birch_trapdoor', 'birch_wood',
  'black_candle', 'black_carpet', 'black_concrete', 'black_concrete_powder', 'black_dye',
  'black_glazed_terracotta', 'black_stained_glass', 'black_stained_glass_pane',
  'black_terracotta', 'black_wool', 'blackstone', 'blackstone_slab', 'blackstone_stairs',
  'blackstone_wall', 'blade_pottery_sherd', 'blast_furnace', 'blaze_powder', 'blaze_rod',
  'blaze_spawn_egg', 'blue_candle', 'blue_carpet', 'blue_concrete', 'blue_concrete_powder',
  'blue_dye', 'blue_glazed_terracotta', 'blue_ice', 'blue_orchid', 'blue_stained_glass',
  'blue_stained_glass_pane', 'blue_terracotta', 'blue_wool', 'bogged_spawn_egg',
  'bolt_armor_trim_smithing_template', 'bone', 'bone_block', 'bone_meal', 'book',
  'bookshelf', 'bowl', 'brain_coral', 'brain_coral_block', 'brain_coral_fan', 'bread',
  'breeze_rod', 'breeze_spawn_egg', 'brewer_pottery_sherd', 'brewing_stand', 'brick',
  'brick_slab', 'brick_stairs', 'brick_wall', 'bricks', 'brown_candle', 'brown_carpet',
  'brown_concrete', 'brown_concrete_powder', 'brown_dye', 'brown_glazed_terracotta',
  'brown_mushroom', 'brown_mushroom_block', 'brown_stained_glass',
  'brown_stained_glass_pane', 'brown_terracotta', 'brown_wool', 'bubble_coral',
  'bubble_coral_block', 'bubble_coral_fan', 'budding_amethyst', 'burn_pottery_sherd',
  'cactus', 'calcite', 'calibrated_sculk_sensor', 'camel_spawn_egg', 'campfire', 'candle',
  'carrot', 'cartography_table', 'carved_pumpkin', 'cat_spawn_egg', 'cauldron',
  'cave_spider_spawn_egg', 'chain', 'chain_command_block', 'charcoal', 'cherry_button',
  'cherry_door', 'cherry_fence', 'cherry_fence_gate', 'cherry_leaves', 'cherry_log',
  'cherry_planks', 'cherry_pressure_plate', 'cherry_sapling', 'cherry_slab',
  'cherry_stairs', 'cherry_trapdoor', 'cherry_wood', 'chest', 'chicken',
  'chicken_spawn_egg', 'chipped_anvil', 'chiseled_bookshelf', 'chiseled_copper',
  'chiseled_deepslate', 'chiseled_nether_bricks', 'chiseled_polished_blackstone',
  'chiseled_quartz_block', 'chiseled_red_sandstone', 'chiseled_sandstone',
  'chiseled_stone_bricks', 'chiseled_tuff', 'chiseled_tuff_bricks', 'chorus_flower',
  'chorus_fruit', 'chorus_plant', 'clay', 'clay_ball', 'clock', 'coal', 'coal_block',
  'coal_ore', 'coarse_dirt', 'coast_armor_trim_smithing_template', 'cobbled_deepslate',
  'cobbled_deepslate_slab', 'cobbled_deepslate_stairs', 'cobbled_deepslate_wall',
  'cobblestone', 'cobblestone_slab', 'cobblestone_stairs', 'cobblestone_wall', 'cobweb',
  'cocoa_beans', 'cod', 'cod_spawn_egg', 'command_block', 'comparator', 'compass',
  'composter', 'conduit', 'cooked_beef', 'cooked_chicken', 'cooked_cod', 'cooked_mutton',
  'cooked_porkchop', 'cooked_rabbit', 'cooked_salmon', 'cookie', 'copper_block',
  'copper_bulb', 'copper_door', 'copper_grate', 'copper_ingot', 'copper_ore',
  'copper_trapdoor', 'cornflower', 'cow_spawn_egg', 'cracked_deepslate_bricks',
  'cracked_deepslate_tiles', 'cracked_nether_bricks', 'cracked_polished_blackstone_bricks',
  'cracked_stone_bricks', 'crafter', 'crafting_table', 'creeper_head', 'creeper_spawn_egg',
  'crimson_button', 'crimson_door', 'crimson_fence', 'crimson_fence_gate', 'crimson_fungus',
  'crimson_hyphae', 'crimson_nylium', 'crimson_planks', 'crimson_pressure_plate',
  'crimson_roots', 'crimson_slab', 'crimson_stairs', 'crimson_stem', 'crimson_trapdoor',
  'crying_obsidian', 'cut_copper', 'cut_copper_slab', 'cut_copper_stairs',
  'cut_red_sandstone', 'cut_red_sandstone_slab', 'cut_sandstone', 'cut_sandstone_slab',
  'cyan_candle', 'cyan_carpet', 'cyan_concrete', 'cyan_concrete_powder', 'cyan_dye',
  'cyan_glazed_terracotta', 'cyan_stained_glass', 'cyan_stained_glass_pane',
  'cyan_terracotta', 'cyan_wool', 'damaged_anvil', 'dandelion', 'danger_pottery_sherd',
  'dark_oak_button', 'dark_oak_door', 'dark_oak_fence', 'dark_oak_fence_gate',
  'dark_oak_leaves', 'dark_oak_log', 'dark_oak_planks', 'dark_oak_pressure_plate',
  'dark_oak_sapling', 'dark_oak_slab', 'dark_oak_stairs', 'dark_oak_trapdoor',
  'dark_oak_wood', 'dark_prismarine', 'dark_prismarine_slab', 'dark_prismarine_stairs',
  'daylight_detector', 'dead_brain_coral', 'dead_brain_coral_block', 'dead_brain_coral_fan',
  'dead_bubble_coral', 'dead_bubble_coral_block', 'dead_bubble_coral_fan', 'dead_bush',
  'dead_fire_coral', 'dead_fire_coral_block', 'dead_fire_coral_fan', 'dead_horn_coral',
  'dead_horn_coral_block', 'dead_horn_coral_fan', 'dead_tube_coral',
  'dead_tube_coral_block', 'dead_tube_coral_fan', 'decorated_pot', 'deepslate',
  'deepslate_brick_slab', 'deepslate_brick_stairs', 'deepslate_brick_wall',
  'deepslate_bricks', 'deepslate_coal_ore', 'deepslate_copper_ore', 'deepslate_diamond_ore',
  'deepslate_emerald_ore', 'deepslate_gold_ore', 'deepslate_iron_ore',
  'deepslate_lapis_ore', 'deepslate_redstone_ore', 'deepslate_tile_slab',
  'deepslate_tile_stairs', 'deepslate_tile_wall', 'deepslate_tiles', 'detector_rail',
  'diamond', 'diamond_block', 'diamond_ore', 'diorite', 'diorite_slab', 'diorite_stairs',
  'diorite_wall', 'dirt', 'dirt_path', 'disc_fragment_5', 'dispenser', 'dolphin_spawn_egg',
  'donkey_spawn_egg', 'dragon_breath', 'dragon_egg', 'dragon_head', 'dried_kelp',
  'dried_kelp_block', 'dripstone_block', 'dropper', 'drowned_spawn_egg',
  'dune_armor_trim_smithing_template', 'echo_shard', 'elder_guardian_spawn_egg', 'emerald',
  'emerald_block', 'emerald_ore', 'enchanted_golden_apple', 'enchanting_table',
  'end_crystal', 'end_portal_frame', 'end_rod', 'end_stone', 'end_stone_brick_slab',
  'end_stone_brick_stairs', 'end_stone_brick_wall', 'end_stone_bricks', 'ender_chest',
  'ender_dragon_spawn_egg', 'ender_eye', 'enderman_spawn_egg', 'endermite_spawn_egg',
  'evoker_spawn_egg', 'experience_bottle', 'explorer_pottery_sherd',
  'exposed_chiseled_copper', 'exposed_copper', 'exposed_copper_bulb', 'exposed_copper_door',
  'exposed_copper_grate', 'exposed_copper_trapdoor', 'exposed_cut_copper',
  'exposed_cut_copper_slab', 'exposed_cut_copper_stairs',
  'eye_armor_trim_smithing_template', 'farmland', 'feather', 'fermented_spider_eye', 'fern',
  'filled_map', 'fire_charge', 'fire_coral', 'fire_coral_block', 'fire_coral_fan',
  'firework_rocket', 'firework_star', 'fletching_table', 'flint',
  'flow_armor_trim_smithing_template', 'flow_pottery_sherd', 'flower_pot',
  'flowering_azalea', 'flowering_azalea_leaves', 'fox_spawn_egg', 'friend_pottery_sherd',
  'frog_spawn_egg', 'frogspawn', 'furnace', 'ghast_spawn_egg', 'ghast_tear',
  'gilded_blackstone', 'glass', 'glass_bottle', 'glass_pane', 'glistering_melon_slice',
  'glow_berries', 'glow_ink_sac', 'glow_item_frame', 'glow_lichen', 'glow_squid_spawn_egg',
  'glowstone', 'glowstone_dust', 'goat_spawn_egg', 'gold_block', 'gold_ingot',
  'gold_nugget', 'gold_ore', 'golden_apple', 'golden_carrot', 'granite', 'granite_slab',
  'granite_stairs', 'granite_wall', 'grass_block', 'gravel', 'gray_candle', 'gray_carpet',
  'gray_concrete', 'gray_concrete_powder', 'gray_dye', 'gray_glazed_terracotta',
  'gray_stained_glass', 'gray_stained_glass_pane', 'gray_terracotta', 'gray_wool',
  'green_candle', 'green_carpet', 'green_concrete', 'green_concrete_powder', 'green_dye',
  'green_glazed_terracotta', 'green_stained_glass', 'green_stained_glass_pane',
  'green_terracotta', 'green_wool', 'grindstone', 'guardian_spawn_egg', 'gunpowder',
  'guster_pottery_sherd', 'hanging_roots', 'hay_block', 'heart_of_the_sea',
  'heart_pottery_sherd', 'heartbreak_pottery_sherd', 'heavy_core',
  'heavy_weighted_pressure_plate', 'hoglin_spawn_egg', 'honey_block', 'honeycomb',
  'honeycomb_block', 'hopper', 'horn_coral', 'horn_coral_block', 'horn_coral_fan',
  'horse_spawn_egg', 'host_armor_trim_smithing_template', 'howl_pottery_sherd',
  'husk_spawn_egg', 'ice', 'infested_chiseled_stone_bricks', 'infested_cobblestone',
  'infested_cracked_stone_bricks', 'infested_deepslate', 'infested_mossy_stone_bricks',
  'infested_stone', 'infested_stone_bricks', 'ink_sac', 'iron_bars', 'iron_block',
  'iron_door', 'iron_golem_spawn_egg', 'iron_ingot', 'iron_nugget', 'iron_ore',
  'iron_trapdoor', 'item_frame', 'jack_o_lantern', 'jigsaw', 'jukebox', 'jungle_button',
  'jungle_door', 'jungle_fence', 'jungle_fence_gate', 'jungle_leaves', 'jungle_log',
  'jungle_planks', 'jungle_pressure_plate', 'jungle_sapling', 'jungle_slab',
  'jungle_stairs', 'jungle_trapdoor', 'jungle_wood', 'kelp', 'ladder', 'lantern',
  'lapis_block', 'lapis_lazuli', 'lapis_ore', 'large_amethyst_bud', 'large_fern', 'lead',
  'leather', 'lectern', 'lever', 'light', 'light_blue_candle', 'light_blue_carpet',
  'light_blue_concrete', 'light_blue_concrete_powder', 'light_blue_dye',
  'light_blue_glazed_terracotta', 'light_blue_stained_glass',
  'light_blue_stained_glass_pane', 'light_blue_terracotta', 'light_blue_wool',
  'light_gray_candle', 'light_gray_carpet', 'light_gray_concrete',
  'light_gray_concrete_powder', 'light_gray_dye', 'light_gray_glazed_terracotta',
  'light_gray_stained_glass', 'light_gray_stained_glass_pane', 'light_gray_terracotta',
  'light_gray_wool', 'light_weighted_pressure_plate', 'lightning_rod', 'lilac',
  'lily_of_the_valley', 'lily_pad', 'lime_candle', 'lime_carpet', 'lime_concrete',
  'lime_concrete_powder', 'lime_dye', 'lime_glazed_terracotta', 'lime_stained_glass',
  'lime_stained_glass_pane', 'lime_terracotta', 'lime_wool', 'llama_spawn_egg', 'lodestone',
  'loom', 'magenta_candle', 'magenta_carpet', 'magenta_concrete', 'magenta_concrete_powder',
  'magenta_dye', 'magenta_glazed_terracotta', 'magenta_stained_glass',
  'magenta_stained_glass_pane', 'magenta_terracotta', 'magenta_wool', 'magma_block',
  'magma_cream', 'magma_cube_spawn_egg', 'mangrove_button', 'mangrove_door',
  'mangrove_fence', 'mangrove_fence_gate', 'mangrove_leaves', 'mangrove_log',
  'mangrove_planks', 'mangrove_pressure_plate', 'mangrove_propagule', 'mangrove_roots',
  'mangrove_slab', 'mangrove_stairs', 'mangrove_trapdoor', 'mangrove_wood', 'map',
  'medium_amethyst_bud', 'melon', 'melon_seeds', 'melon_slice', 'miner_pottery_sherd',
  'mooshroom_spawn_egg', 'moss_block', 'moss_carpet', 'mossy_cobblestone',
  'mossy_cobblestone_slab', 'mossy_cobblestone_stairs', 'mossy_cobblestone_wall',
  'mossy_stone_brick_slab', 'mossy_stone_brick_stairs', 'mossy_stone_brick_wall',
  'mossy_stone_bricks', 'mourner_pottery_sherd', 'mud', 'mud_brick_slab',
  'mud_brick_stairs', 'mud_brick_wall', 'mud_bricks', 'muddy_mangrove_roots',
  'mule_spawn_egg', 'mushroom_stem', 'mutton', 'mycelium', 'name_tag', 'nautilus_shell',
  'nether_brick', 'nether_brick_fence', 'nether_brick_slab', 'nether_brick_stairs',
  'nether_brick_wall', 'nether_bricks', 'nether_gold_ore', 'nether_quartz_ore',
  'nether_sprouts', 'nether_star', 'nether_wart', 'nether_wart_block', 'netherite_block',
  'netherite_ingot', 'netherite_scrap', 'netherite_upgrade_smithing_template', 'netherrack',
  'note_block', 'oak_button', 'oak_door', 'oak_fence', 'oak_fence_gate', 'oak_leaves',
  'oak_log', 'oak_planks', 'oak_pressure_plate', 'oak_sapling', 'oak_slab', 'oak_stairs',
  'oak_trapdoor', 'oak_wood', 'observer', 'obsidian', 'ocelot_spawn_egg', 'ochre_froglight',
  'ominous_bottle', 'ominous_trial_key', 'orange_candle', 'orange_carpet',
  'orange_concrete', 'orange_concrete_powder', 'orange_dye', 'orange_glazed_terracotta',
  'orange_stained_glass', 'orange_stained_glass_pane', 'orange_terracotta', 'orange_tulip',
  'orange_wool', 'oxeye_daisy', 'oxidized_chiseled_copper', 'oxidized_copper',
  'oxidized_copper_bulb', 'oxidized_copper_door', 'oxidized_copper_grate',
  'oxidized_copper_trapdoor', 'oxidized_cut_copper', 'oxidized_cut_copper_slab',
  'oxidized_cut_copper_stairs', 'packed_ice', 'packed_mud', 'painting', 'panda_spawn_egg',
  'paper', 'parrot_spawn_egg', 'pearlescent_froglight', 'peony', 'petrified_oak_slab',
  'phantom_membrane', 'phantom_spawn_egg', 'pig_spawn_egg', 'piglin_brute_spawn_egg',
  'piglin_head', 'piglin_spawn_egg', 'pillager_spawn_egg', 'pink_candle', 'pink_carpet',
  'pink_concrete', 'pink_concrete_powder', 'pink_dye', 'pink_glazed_terracotta',
  'pink_petals', 'pink_stained_glass', 'pink_stained_glass_pane', 'pink_terracotta',
  'pink_tulip', 'pink_wool', 'piston', 'pitcher_plant', 'pitcher_pod', 'player_head',
  'plenty_pottery_sherd', 'podzol', 'pointed_dripstone', 'poisonous_potato',
  'polar_bear_spawn_egg', 'polished_andesite', 'polished_andesite_slab',
  'polished_andesite_stairs', 'polished_basalt', 'polished_blackstone',
  'polished_blackstone_brick_slab', 'polished_blackstone_brick_stairs',
  'polished_blackstone_brick_wall', 'polished_blackstone_bricks',
  'polished_blackstone_button', 'polished_blackstone_pressure_plate',
  'polished_blackstone_slab', 'polished_blackstone_stairs', 'polished_blackstone_wall',
  'polished_deepslate', 'polished_deepslate_slab', 'polished_deepslate_stairs',
  'polished_deepslate_wall', 'polished_diorite', 'polished_diorite_slab',
  'polished_diorite_stairs', 'polished_granite', 'polished_granite_slab',
  'polished_granite_stairs', 'polished_tuff', 'polished_tuff_slab', 'polished_tuff_stairs',
  'polished_tuff_wall', 'popped_chorus_fruit', 'poppy', 'porkchop', 'potato',
  'powered_rail', 'prismarine', 'prismarine_brick_slab', 'prismarine_brick_stairs',
  'prismarine_bricks', 'prismarine_crystals', 'prismarine_shard', 'prismarine_slab',
  'prismarine_stairs', 'prismarine_wall', 'prize_pottery_sherd', 'pufferfish',
  'pufferfish_spawn_egg', 'pumpkin', 'pumpkin_pie', 'pumpkin_seeds', 'purple_candle',
  'purple_carpet', 'purple_concrete', 'purple_concrete_powder', 'purple_dye',
  'purple_glazed_terracotta', 'purple_stained_glass', 'purple_stained_glass_pane',
  'purple_terracotta', 'purple_wool', 'purpur_block', 'purpur_pillar', 'purpur_slab',
  'purpur_stairs', 'quartz', 'quartz_block', 'quartz_bricks', 'quartz_pillar',
  'quartz_slab', 'quartz_stairs', 'rabbit', 'rabbit_foot', 'rabbit_hide',
  'rabbit_spawn_egg', 'rail', 'raiser_armor_trim_smithing_template', 'ravager_spawn_egg',
  'raw_copper', 'raw_copper_block', 'raw_gold', 'raw_gold_block', 'raw_iron',
  'raw_iron_block', 'recovery_compass', 'red_candle', 'red_carpet', 'red_concrete',
  'red_concrete_powder', 'red_dye', 'red_glazed_terracotta', 'red_mushroom',
  'red_mushroom_block', 'red_nether_brick_slab', 'red_nether_brick_stairs',
  'red_nether_brick_wall', 'red_nether_bricks', 'red_sand', 'red_sandstone',
  'red_sandstone_slab', 'red_sandstone_stairs', 'red_sandstone_wall', 'red_stained_glass',
  'red_stained_glass_pane', 'red_terracotta', 'red_tulip', 'red_wool', 'redstone',
  'redstone_block', 'redstone_lamp', 'redstone_ore', 'redstone_torch',
  'reinforced_deepslate', 'repeater', 'repeating_command_block', 'respawn_anchor',
  'rib_armor_trim_smithing_template', 'rooted_dirt', 'rose_bush', 'rotten_flesh', 'salmon',
  'salmon_spawn_egg', 'sand', 'sandstone', 'sandstone_slab', 'sandstone_stairs',
  'sandstone_wall', 'scaffolding', 'scrape_pottery_sherd', 'sculk', 'sculk_catalyst',
  'sculk_sensor', 'sculk_shrieker', 'sculk_vein', 'sea_lantern', 'sea_pickle', 'seagrass',
  'sentry_armor_trim_smithing_template', 'shaper_armor_trim_smithing_template',
  'sheaf_pottery_sherd', 'sheep_spawn_egg', 'shelter_pottery_sherd', 'short_grass',
  'shroomlight', 'shulker_shell', 'shulker_spawn_egg',
  'silence_armor_trim_smithing_template', 'silverfish_spawn_egg',
  'skeleton_horse_spawn_egg', 'skeleton_skull', 'skeleton_spawn_egg', 'skull_pottery_sherd',
  'slime_ball', 'slime_block', 'slime_spawn_egg', 'small_amethyst_bud', 'small_dripleaf',
  'smithing_table', 'smoker', 'smooth_basalt', 'smooth_quartz', 'smooth_quartz_slab',
  'smooth_quartz_stairs', 'smooth_red_sandstone', 'smooth_red_sandstone_slab',
  'smooth_red_sandstone_stairs', 'smooth_sandstone', 'smooth_sandstone_slab',
  'smooth_sandstone_stairs', 'smooth_stone', 'smooth_stone_slab', 'sniffer_egg',
  'sniffer_spawn_egg', 'snort_pottery_sherd', 'snout_armor_trim_smithing_template', 'snow',
  'snow_block', 'snow_golem_spawn_egg', 'soul_campfire', 'soul_lantern', 'soul_sand',
  'soul_soil', 'soul_torch', 'spawner', 'spectral_arrow', 'spider_eye', 'spider_spawn_egg',
  'spire_armor_trim_smithing_template', 'sponge', 'spore_blossom', 'spruce_button',
  'spruce_door', 'spruce_fence', 'spruce_fence_gate', 'spruce_leaves', 'spruce_log',
  'spruce_planks', 'spruce_pressure_plate', 'spruce_sapling', 'spruce_slab',
  'spruce_stairs', 'spruce_trapdoor', 'spruce_wood', 'squid_spawn_egg', 'stick',
  'sticky_piston', 'stone', 'stone_brick_slab', 'stone_brick_stairs', 'stone_brick_wall',
  'stone_bricks', 'stone_button', 'stone_pressure_plate', 'stone_slab', 'stone_stairs',
  'stonecutter', 'stray_spawn_egg', 'strider_spawn_egg', 'string', 'stripped_acacia_log',
  'stripped_acacia_wood', 'stripped_bamboo_block', 'stripped_birch_log',
  'stripped_birch_wood', 'stripped_cherry_log', 'stripped_cherry_wood',
  'stripped_crimson_hyphae', 'stripped_crimson_stem', 'stripped_dark_oak_log',
  'stripped_dark_oak_wood', 'stripped_jungle_log', 'stripped_jungle_wood',
  'stripped_mangrove_log', 'stripped_mangrove_wood', 'stripped_oak_log',
  'stripped_oak_wood', 'stripped_spruce_log', 'stripped_spruce_wood',
  'stripped_warped_hyphae', 'stripped_warped_stem', 'structure_block', 'structure_void',
  'sugar', 'sugar_cane', 'sunflower', 'suspicious_gravel', 'suspicious_sand',
  'sweet_berries', 'tadpole_spawn_egg', 'tall_grass', 'target', 'terracotta',
  'tide_armor_trim_smithing_template', 'tinted_glass', 'tipped_arrow', 'tnt', 'torch',
  'torchflower', 'torchflower_seeds', 'trader_llama_spawn_egg', 'trapped_chest',
  'trial_key', 'trial_spawner', 'tripwire_hook', 'tropical_fish', 'tropical_fish_spawn_egg',
  'tube_coral', 'tube_coral_block', 'tube_coral_fan', 'tuff', 'tuff_brick_slab',
  'tuff_brick_stairs', 'tuff_brick_wall', 'tuff_bricks', 'tuff_slab', 'tuff_stairs',
  'tuff_wall', 'turtle_egg', 'turtle_scute', 'turtle_spawn_egg', 'twisting_vines', 'vault',
  'verdant_froglight', 'vex_armor_trim_smithing_template', 'vex_spawn_egg',
  'villager_spawn_egg', 'vindicator_spawn_egg', 'vine', 'wandering_trader_spawn_egg',
  'ward_armor_trim_smithing_template', 'warden_spawn_egg', 'warped_button', 'warped_door',
  'warped_fence', 'warped_fence_gate', 'warped_fungus', 'warped_hyphae', 'warped_nylium',
  'warped_planks', 'warped_pressure_plate', 'warped_roots', 'warped_slab', 'warped_stairs',
  'warped_stem', 'warped_trapdoor', 'warped_wart_block', 'waxed_chiseled_copper',
  'waxed_copper_block', 'waxed_copper_bulb', 'waxed_copper_door', 'waxed_copper_grate',
  'waxed_copper_trapdoor', 'waxed_cut_copper', 'waxed_cut_copper_slab',
  'waxed_cut_copper_stairs', 'waxed_exposed_chiseled_copper', 'waxed_exposed_copper',
  'waxed_exposed_copper_bulb', 'waxed_exposed_copper_door', 'waxed_exposed_copper_grate',
  'waxed_exposed_copper_trapdoor', 'waxed_exposed_cut_copper',
  'waxed_exposed_cut_copper_slab', 'waxed_exposed_cut_copper_stairs',
  'waxed_oxidized_chiseled_copper', 'waxed_oxidized_copper', 'waxed_oxidized_copper_bulb',
  'waxed_oxidized_copper_door', 'waxed_oxidized_copper_grate',
  'waxed_oxidized_copper_trapdoor', 'waxed_oxidized_cut_copper',
  'waxed_oxidized_cut_copper_slab', 'waxed_oxidized_cut_copper_stairs',
  'waxed_weathered_chiseled_copper', 'waxed_weathered_copper',
  'waxed_weathered_copper_bulb', 'waxed_weathered_copper_door',
  'waxed_weathered_copper_grate', 'waxed_weathered_copper_trapdoor',
  'waxed_weathered_cut_copper', 'waxed_weathered_cut_copper_slab',
  'waxed_weathered_cut_copper_stairs', 'wayfinder_armor_trim_smithing_template',
  'weathered_chiseled_copper', 'weathered_copper', 'weathered_copper_bulb',
  'weathered_copper_door', 'weathered_copper_grate', 'weathered_copper_trapdoor',
  'weathered_cut_copper', 'weathered_cut_copper_slab', 'weathered_cut_copper_stairs',
  'weeping_vines', 'wet_sponge', 'wheat', 'wheat_seeds', 'white_candle', 'white_carpet',
  'white_concrete', 'white_concrete_powder', 'white_dye', 'white_glazed_terracotta',
  'white_stained_glass', 'white_stained_glass_pane', 'white_terracotta', 'white_tulip',
  'white_wool', 'wild_armor_trim_smithing_template', 'wind_charge', 'witch_spawn_egg',
  'wither_rose', 'wither_skeleton_skull', 'wither_skeleton_spawn_egg', 'wither_spawn_egg',
  'wolf_spawn_egg', 'yellow_candle', 'yellow_carpet', 'yellow_concrete',
  'yellow_concrete_powder', 'yellow_dye', 'yellow_glazed_terracotta',
  'yellow_stained_glass', 'yellow_stained_glass_pane', 'yellow_terracotta', 'yellow_wool',
  'zoglin_spawn_egg', 'zombie_head', 'zombie_horse_spawn_egg', 'zombie_spawn_egg',
  'zombie_villager_spawn_egg', 'zombified_piglin_spawn_egg',
]

/** 生成元の Minecraft バージョン (テストで参照する)。 */
export const ITEM_STACK_MC_VERSION = '1.21.1'

/** 生成時点の全アイテム数 (取得内容が壊れていないかの目安)。 */
export const ITEM_STACK_TOTAL = 1333
