export { CircuitEditor } from './editor.js'
export type { PlaceableType, PlaceOptions } from './editor.js'
export { EditorGrid } from './grid.js'
export type { Pos2D, EditAction } from './grid.js'
export { computeWireConnections, collectWireConnectionUpdates } from './wire-connect.js'
export type { GridPos, BlockGrid3D } from './wire-connect.js'
